// <auto-generated />
using BlogApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20241223082255_INIT")]
    partial class INIT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BlogApp.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Oyun"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sinema"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Spor"
                        });
                });

            modelBuilder.Entity("BlogApp.Entities.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Contents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Text = "merhaba bu ilk gönderinin metnidir.",
                            Title = "İlk Paylaşım"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Text = "merhaba bu ikinci gönderinin metnidir.",
                            Title = "İkinci Paylaşım"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Text = "merhaba bu üçüncü gönderinin metnidir.",
                            Title = "Üçüncü Paylaşım"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Text = "adfnkdajfj kkjdanf kjdaaakj kjda jnqje  nkjndskjf kjsdkjnqw nkqnwkas",
                            Title = "Deneme Başlık"
                        });
                });

            modelBuilder.Entity("BlogApp.Entities.Content", b =>
                {
                    b.HasOne("BlogApp.Entities.Category", "Category")
                        .WithMany("Contents")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BlogApp.Entities.Category", b =>
                {
                    b.Navigation("Contents");
                });
#pragma warning restore 612, 618
        }
    }
}
